set -g mouse on

# change C-b to C-a
unbind C-b
set-option -g prefix ` 
bind-key ` send-prefix

# start window at 1
set -g base-index 1
setw -g pane-base-index 1

source /usr/share/powerline/bindings/tmux/powerline.conf
set -g default-terminal "screen-256color"
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"
bind-key ! break-pane
