[ids]
0001:0001

[main]
e = f
r = p
t = g
y = j
u = l
i = u
o = y
p = semicolon
g = d
n = k

# --- Homerow Mods ---
# O overload() em teclas alfabéticas já possui o comportamento padrão de
# repetir a tecla se for feito o movimento de "tap and hold" (duplo clique segurando).
a = overloadt(meta, a, 300)
s = overloadt(alt, r, 200)
d = overloadt(control, s, 200)
f = overloadt(shift, t, 200)

j = overloadt(shift, n, 200)
k = overloadt(control, e, 200)
l = overloadt(alt, i, 200)
; = overloadt(meta, o, 300)

z = overloadt(altgr, z, 200)
/ = overloadt(altgr, /, 200)

c = timeout(c, 150, macro(rightalt+,))
leftshift = oneshot(shift)

# --- Chords ---
u+i = backspace
i+o = delete
j+k = escape
k+l = C-M-A-S-f12
s+d = tab
z+x = C-x
x+c = C-c
c+v = C-v
d+f = C-S-t

f15 = oneshot(greek)

# --- Capslock: Sticky, Hold & Toggle ---
# oneshot() realiza a função de sticky (único comando) com 1 toque,
# e ativa a camada enquanto é segurado.
capslock = oneshot(nav)

# --- AltGr: Sticky Shift ---
rightalt = oneshot(shift_tapdance)
leftalt = oneshot(shift_tapdance)

# --- Camada Customizável do Espaço ---
space = overloadt(numsnsym, space, 200)

[altgr]
x = ^
c = macro(rightalt+,)

[shift_tapdance:S]
rightalt = toggle(capsword)
leftalt = toggle(capsword)

[greek]
q = macro(θ)
w = macro(ω)
f = macro(φ)
p = macro(π)
g = macro(γ)
j = macro(ξ)
l = macro(λ)
u = macro(υ)
y = macro(ψ)
a = macro(α)
r = macro(ρ)
s = macro(σ)
t = macro(τ)
d = macro(δ)
h = macro(η)
n = macro(ν)
e = macro(ε)
i = macro(ι)
o = macro(ο)
z = macro(ζ)
x = macro(χ)
c = macro(ς)
v = macro(ς)
b = macro(β)
k = macro(κ)
m = macro(μ)


[nav]
# O primeiro clique do capslock ativa oneshot(nav), logo, o segundo clique
# é interceptado por esta camada. Definir como toggle(nav) cria o comportamento
# exato de duplo-clique para travar/destravar (toggle).
capslock = toggle(nav)
space = enter

i = up
j = left
k = down
l = right
u = home
y = pageup
h = pagedown
o = end
p = delete
; = backspace
' = escape
enter = print
n = volumedown
m = mute
comma = volumeup
e = nextsong
w = playpause
q = previoussong
z = C-z
x = C-x
c = C-c
v = C-v

[numsnsym]
a = !
s = @
d = #
f = $
g = %
h = ^
j = &
k = *
l = (
; = )

z = 1
x = 2
c = 3
v = 4
b = 5
n = 6
m = 7
, = 8
. = 9
/ = 0
' = -
\ = =

q = f1
w = f2
e = f3
r = f4
t = f5
y = f6
u = f7
i = f8
o = f9
p = f10

[capsword:S]

backspace = backspace

1 = togglem(capsword, 1)
2 = togglem(capsword, 2)
3 = togglem(capsword, 3)
4 = togglem(capsword, 4)
5 = togglem(capsword, 5)
6 = togglem(capsword, 6)
7 = togglem(capsword, 7)
8 = togglem(capsword, 8)
9 = togglem(capsword, 9)
0 = togglem(capsword, 0)

# Saem do capsword e inserem o próprio caractere (pontuações e controles)
. = togglem(capsword, .)
, = togglem(capsword, ,)
/ = togglem(capsword, /)
- = togglem(capsword, -)
= = togglem(capsword, =)
' = togglem(capsword, ')
; = togglem(capsword, ;)
[ = togglem(capsword, [)
] = togglem(capsword, ])
\ = togglem(capsword, \)
` = togglem(capsword, `)

enter = togglem(capsword, enter)
tab = togglem(capsword, tab)
escape = clear()
space = togglem(capsword, space)
, = togglem(capsword, comma)
. = togglem(capsword, dot)