[ids]
0001:0001

[main]
# --- Homerow Mods ---
# O overload() em teclas alfabéticas já possui o comportamento padrão de
# repetir a tecla se for feito o movimento de "tap and hold" (duplo clique segurando).
a = overloadt(meta, a, 300)
s = overloadt(alt, s, 200)
d = overloadt(control, d, 200)
f = overloadt(shift, f, 200)

j = overloadt(shift, j, 200)
k = overloadt(control, k, 200)
l = overloadt(alt, l, 200)
; = overloadt(meta, ;, 300)

z = overloadt(altgr, z, 300)
/ = overloadt(altgr, /, 300)

c = timeout(c, 300, macro(rightalt+c))
leftshift = oneshot(shift)

# --- Chords ---
u+i = backspace
i+o = delete
j+k = escape
k+l = C-M-A-S-f12
s+d = tab


# --- Capslock: Sticky, Hold & Toggle ---
# oneshot() realiza a função de sticky (único comando) com 1 toque,
# e ativa a camada enquanto é segurado.
capslock = oneshot(nav)

# --- AltGr: Sticky Shift ---
rightalt = oneshot(shift)

# --- Camada Customizável do Espaço ---
space = overloadt(numsnsym, space, 200)


[nav]
# O primeiro clique do capslock ativa oneshot(nav), logo, o segundo clique
# é interceptado por esta camada. Definir como toggle(nav) cria o comportamento
# exato de duplo-clique para travar/destravar (toggle).
capslock = toggle(nav)
space = enter

i = up
j = left
k = down
l = right
u = home
y = pageup
h = pagedown
o = end
p = delete
; = backspace
' = escape
enter = print
n = volumedown
m = mute
comma = volumeup
e = nextsong
w = playpause
q = previoussong
z = C-z
x = C-x
c = C-c
v = C-v

[numsnsym]
a = !
s = @
d = #
f = $
g = %
h = ^
j = &
k = *
l = (
; = )

z = 1
x = 2
c = 3
v = 4
b = 5
n = 6
m = 7
, = 8
. = 9
/ = 0

q = f1
w = f2
e = f3
r = f4
t = f5
y = f6
u = f7
i = f8
o = f9
p = f10
